# -*- coding: utf-8 -*-
"""0916.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sNO55fq-RI8LJ6Okls6Sff3YK7baTnbi

print("文字")；
print(變數)；
a=input():a為輸入的結果:(a的資料型態為string)；
a=int(input()):a為輸入的結果:(a的資料型態為int)
"""

print("Hello World")

a="王則文"
b="你好呀"
print(a+b)
print("a+b")
print(b+a)

a="hello"
b=input()
print(a+b)

num1=10
num2=5
print(num1+num2)

num1=int(input())
num2=int(input())
print(num1+num2)